export const NAVIGATE_MATCH_SCREEN = "NAVIGATE_MATCH_SCREEN";
export const REDUX_INIT = "@@redux/INIT";

export const REQUEST_MATCH_DETAILS = "REQUEST_MATCH_DETAILS";
export const RECEIVE_MATCH_DETAILS = "RECEIVE_MATCH_DETAILS";
export const RECEIVE_EMPTY_MATCH_DETAILS = "RECEIVE_EMPTY_MATCH_DETAILS";

export const REQUEST_PROMATCH_DETAILS = "REQUEST_PROMATCH_DETAILS";
export const RECEIVE_PROMATCH_DETAILS = "RECEIVE_PROMATCH_DETAILS";
export const RECEIVE_EMPTY_PROMATCH_DETAILS = "RECEIVE_EMPTY_PROMATCH_DETAILS";

export const REQUEST_HIGHMMR_MATCH_DETAILS = "REQUEST_HIGHMMR_MATCH_DETAILS";
export const RECEIVE_HIGHMMR_MATCH_DETAILS = "RECEIVE_HIGHMMR_MATCH_DETAILS";
export const RECEIVE_EMPTY_HIGHMMR_MATCH_DETAILS =
  "RECEIVE_EMPTY_HIGHMMR_MATCH_DETAILS";

export const REQUEST_LOW_MMR_MATCH_DETAILS = "REQUEST_LOW_MMR_MATCH_DETAILS";
export const RECEIVE_LOW_MMR_MATCH_DETAILS = "RECEIVE_LOW_MMR_MATCH_DETAILS";
export const RECEIVE_EMPTY_LOW_MMR_MATCH_DETAILS =
  "RECEIVE_EMPTY_LOW_MMR_MATCH_DETAILS";

export const REQUEST_PLAYERS = "REQUEST_PLAYERS";
export const RECEIVE_PLAYERS = "RECEIVE_PLAYERS";
export const RECEIVE_PRO_PLAYERS = "RECEIVE_PRO_PLAYERS";
export const RECEIVE_EMPTY_PLAYERS = "RECEIVE_EMPTY_PLAYERS";

export const REQUEST_HERO_STATS = "REQUEST_HERO_STATS";
export const RECEIVE_HERO_STATS = "RECEIVE_HERO_STATS";
export const RECEIVE_EMPTY_HERO_STATS = "RECEIVE_EMPTY_HERO_STATS";

export const REQUEST_HERO_RANKING = "REQUEST_HERO_RANKING";
export const RECEIVE_HERO_RANKING = "RECEIVE_HERO_RANKING";
export const RECEIVE_EMPTY_HERO_RANKING = "RECEIVE_EMPTY_HERO_RANKING";

export const SEND_HERO_DATA="SEND_HERO_DATA";

export const REQUEST_DURATION_RECORD = "REQUEST_DURATION_RECORD";
export const RECEIVE_DURATION_RECORD = "RECEIVE_DURATION_RECORD";
export const RECEIVE_EMPTY_DURATION_RECORD = "REQUEST_EMPTY_DURATION_RECORD";

export const REQUEST_KILLS_RECORD = "REQUEST_KILLS_RECORD";
export const RECEIVE_KILLS_RECORD = "RECEIVE_KILLS_RECORD";
export const RECEIVE_EMPTY_KILLS_RECORD = "REQUEST_EMPTY_KILLS_RECORD";

export const REQUEST_DEATHS_RECORD = "REQUEST_DEATHS_RECORD";
export const RECEIVE_DEATHS_RECORD = "RECEIVE_DEATHS_RECORD";
export const RECEIVE_EMPTY_DEATHS_RECORD = "RECEIVE_EMPTY_DEATHS_RECORD";

export const REQUEST_ASSISTS_RECORD = "REQUEST_ASSISTS_RECORD";
export const RECEIVE_ASSISTS_RECORD = "RECEIVE_ASSISTS_RECORD";
export const RECEIVE_EMPTY_ASSISTS_RECORD = "RECEIVE_EMPTY_ASSISTS_RECORD";

export const REQUEST_GPM_RECORD = "REQUEST_GPM_RECORD";
export const RECEIVE_GPM_RECORD = "RECEIVE_GPM_RECORD";
export const RECEIVE_EMPTY_GPM_RECORD = "RECEIVE_EMPTY_GPM_RECORD";

export const REQUEST_XPM_RECORD = "REQUEST_XPM_RECORD";
export const RECEIVE_XPM_RECORD = "RECEIVE_XPM_RECORD";
export const RECEIVE_EMPTY_XPM_RECORD = "RECEIVE_EMPTY_XPM_RECORD";

export const REQUEST_LH_RECORD = "REQUEST_LH_RECORD";
export const RECEIVE_LH_RECORD = "RECEIVE_LH_RECORD";
export const RECEIVE_EMPTY_LH_RECORD = "RECEIVE_EMPTY_LH_RECORD";

export const REQUEST_DN_RECORD = "REQUEST_DN_RECORD";
export const RECEIVE_DN_RECORD = "RECEIVE_DN_RECORD";
export const RECEIVE_EMPTY_DN_RECORD = "RECEIVE_EMPTY_DN_RECORD";

export const REQUEST_HD_RECORD = "REQUEST_HD_RECORD";
export const RECEIVE_HD_RECORD = "RECEIVE_HD_RECORD";
export const RECEIVE_EMPTY_HD_RECORD = "RECEIVE_EMPTY_HD_RECORD";

export const REQUEST_TD_RECORD = "REQUEST_TD_RECORD";
export const RECEIVE_TD_RECORD = "RECEIVE_TD_RECORD";
export const RECEIVE_EMPTY_TD_RECORD = "RECEIVE_EMPTY_TD_RECORD";

export const REQUEST_HH_RECORD = "REQUEST_HH_RECORD";
export const RECEIVE_HH_RECORD = "RECEIVE_HH_RECORD";
export const RECEIVE_EMPTY_HH_RECORD = "RECEIVE_EMPTY_HH_RECORD";

