export const NAVIGATE_MATCH_SCREEN = "NAVIGATE_MATCH_SCREEN";
export const REDUX_INIT = "@@redux/INIT";

export const REQUEST_MATCH_DETAILS = "REQUEST_MATCH_DETAILS";
export const RECEIVE_MATCH_DETAILS = "RECEIVE_MATCH_DETAILS";
export const RECEIVE_EMPTY_MATCH_DETAILS = "RECEIVE_EMPTY_MATCH_DETAILS";

export const REQUEST_PROMATCH_DETAILS = "REQUEST_PROMATCH_DETAILS";
export const RECEIVE_PROMATCH_DETAILS = "RECEIVE_PROMATCH_DETAILS";
export const RECEIVE_EMPTY_PROMATCH_DETAILS = "RECEIVE_EMPTY_PROMATCH_DETAILS";

export const REQUEST_HIGHMMR_MATCH_DETAILS = "REQUEST_HIGHMMR_MATCH_DETAILS";
export const RECEIVE_HIGHMMR_MATCH_DETAILS = "RECEIVE_HIGHMMR_MATCH_DETAILS";
export const RECEIVE_EMPTY_HIGHMMR_MATCH_DETAILS =
  "RECEIVE_EMPTY_HIGHMMR_MATCH_DETAILS";

export const REQUEST_LOW_MMR_MATCH_DETAILS = "REQUEST_LOW_MMR_MATCH_DETAILS";
export const RECEIVE_LOW_MMR_MATCH_DETAILS = "RECEIVE_LOW_MMR_MATCH_DETAILS";
export const RECEIVE_EMPTY_LOW_MMR_MATCH_DETAILS =
  "RECEIVE_EMPTY_LOW_MMR_MATCH_DETAILS";

export const REQUEST_PLAYERS = "REQUEST_PLAYERS";
export const RECEIVE_PLAYERS = "RECEIVE_PLAYERS";
export const RECEIVE_PRO_PLAYERS = "RECEIVE_PRO_PLAYERS";
export const RECEIVE_EMPTY_PLAYERS = "RECEIVE_EMPTY_PLAYERS";

export const REQUEST_HERO_STATS = "REQUEST_HERO_STATS";
export const RECEIVE_HERO_STATS = "RECEIVE_HERO_STATS";
export const RECEIVE_EMPTY_HERO_STATS = "RECEIVE_EMPTY_HERO_STATS";

export const REQUEST_HERO_RANKING = "REQUEST_HERO_RANKING";
export const RECEIVE_HERO_RANKING = "RECEIVE_HERO_RANKING";
export const RECEIVE_EMPTY_HERO_RANKING = "RECEIVE_EMPTY_HERO_RANKING";

export const SEND_HERO_DATA="SEND_HERO_DATA";

